swagger: '2.0'
info:
  version: '1.0'
  title: "Documentazione API"

host: wave-edu-server.onrender.com:8080
basePath: /api
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /user:
    post:
      tags:
        - User
      summary: Create a new user
      parameters:
        - name: body
          in: body
          description: User object
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              name:
                type: string
              userType:
                type: string
      responses:
        "201":
          description: Created 
    get:
      tags:
        - User
      summary: Get all users
      security:
        - teacher: []
      responses:
        "200":
          description: Successful Response
          schema:
            type: object
            properties:
              email:
                type: string
              name:
                type: string
              userType:
                type: string

    delete:
      tags:
        - User
      summary: Delete all users
      security:
        - teacher: []
      responses:
        "204":
          description: No Content
          
  /user/{id}:
    get:
      tags:
        - User
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          description: ID of user to retrieve
          required: true
          type: string
      responses:
        "200":
          description: Successful Response
          schema:
            type: object
            properties:
              email:
                type: string
              name:
                type: string
              userType:
                type: string
    put:
      tags:
        - User
      summary: Update user by ID
      parameters:
        - name: id
          in: path
          description: ID of user to update
          required: true
          type: string
      responses:
        "200":
          description: OK
    delete:
      tags:
        - User
      summary: Delete user by ID
      parameters:
        - name: id
          in: path
          description: ID of user to delete
          required: true
          type: string
      responses:
        "204":
          description: No Content          
          
securityDefinitions:
  teacher:
    type: apiKey
    name: Authorization
    in: header
    description: Requires teacher authorization to access this endpoint.